import = [
    "~/.config/alacritty/themes/themes/omni.toml"
]

[window]
decorations = "Full"
opacity = 0.80
blur = true
startup_mode = "Fullscreen"
dynamic_title = false
resize_increments = true

[scrolling]
history = 5000

[font]
normal = { family = "FiraCode Nerd Font Mono", style = "Retina" }
size = 20
builtin_box_drawing = false

[colors]
transparent_background_colors = true

[cursor]
style = { blinking = "Always" }
blink_timeout = 0

[keyboard]
bindings = [
    { key = "V", mods = "Command|Shift", action = "ToggleViMode" }
]

